name: kuis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: mons
      fonts:
        - asset: assets/fonts/mons.ttf
          weight: 700
  assets:
    - assets/images/
  
